run:
  timeout: 3m

issues:
  max-issues-per-linter: 10
  max-same-issues: 10

linters:
  enable-all: true
  fast: true
  disable:
    - misspell
    - lll
    - wsl
    - depguard
    - scopelint
    - nosnakecase
    - ifshort
    - gocognit
    - gochecknoinits
    - dupl
    - testpackage
    - tagliatelle
    - interfacebloat
    - forcetypeassert

linters-settings:
  goheader:
    values:
      const:
        COMPANY: MpesaOverlay
    template: |-
      Copyright (c) {{ COMPANY }}. All rights reserved.
      Use of this source code is governed by a Apache-2.0 license that can be
      found in the LICENSE file.

      SPDX-License-Identifier: Apache-2.0
  funlen:
    lines: -1
    statements: -1
  gomnd:
    ignored-files:
      - "example/.*/.*/main.go"
