# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

project_name: mpesaoverlay

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/cli
    id: "mpesaoverlay-cli"
    binary: mpesa-cli
    ldflags:
      - "-s -w -X github.com/0x6flab/mpesaoverlay.Version={{.Version}} -X github.com/0x6flab/mpesaoverlay.Commit={{.FullCommit}} -X github.com/0x6flab/mpesaoverlay.BuildTime={{.Timestamp}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386

  - main: ./cmd/grpc
    id: "mpesaoverlay-grpc"
    binary: mpesa-grpc
    ldflags:
      - "-s -w -X github.com/0x6flab/mpesaoverlay.Version={{.Version}} -X github.com/0x6flab/mpesaoverlay.Commit={{.FullCommit}} -X github.com/0x6flab/mpesaoverlay.BuildTime={{.Timestamp}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386

  - main: ./cmd/mqtt
    id: "mpesaoverlay-mqtt"
    binary: mpesa-mqtt
    ldflags:
      - "-s -w -X github.com/0x6flab/mpesaoverlay.Version={{.Version}} -X github.com/0x6flab/mpesaoverlay.Commit={{.FullCommit}} -X github.com/0x6flab/mpesaoverlay.BuildTime={{.Timestamp}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}-source"
