{
 "title": "Example Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "gRPC Adapater Logs",
   "type": "logs",
   "description": "Logs from grpc adapter container",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"mpesaoverlay-grpc\"} |= ``"
    }
   ]
  },
  {
   "title": "MQTT adapter logs",
   "type": "logs",
   "description": "Logs from mqtt adapter container",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"mpesaoverlay-mqtt\"} |= ``"
    }
   ]
  },
  {
   "title": "Traefik Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"mpesaoverlay-traefik\"} |= ``"
    }
   ]
  }
 ]
}