package mpesa

// ExpressSimulateReq struct.
type ExpressSimulateReq struct {
	PassKey           string `json:"PassKey,omitempty"`           // This is a passkey which is generated by Safaricom for use when making Lipa Na M-Pesa Online Payment API requests.
	BusinessShortCode uint64 `json:"BusinessShortCode,omitempty"` // This is the organization's shortcode (Paybill or Buygoods - A 5 to 6-digit account number) used to identify an organization and receive the transaction.
	Password          string `json:"Password,omitempty"`          // This is the password used for encrypting the request sent.
	Timestamp         string `json:"Timestamp,omitempty"`         // This is the Timestamp of the transaction.
	TransactionType   string `json:"TransactionType,omitempty"`   // This is the transaction type that is used to identify the transaction when sending the request to M-PESA.
	PhoneNumber       uint64 `json:"PhoneNumber,omitempty"`       // The Mobile Number to receive the STK Pin Prompt.
	Amount            uint64 `json:"Amount,omitempty"`            // This is the Amount transacted normally a numeric value.
	PartyA            uint64 `json:"PartyA,omitempty"`            // The phone number sending money.
	PartyB            uint64 `json:"PartyB,omitempty"`            // The organization that receives the funds.
	CallBackURL       string `json:"CallBackURL,omitempty"`       // A CallBack URL is a valid secure URL that is used to receive notifications from M-Pesa API.
	AccountReference  string `json:"AccountReference,omitempty"`  // This is an Alpha-Numeric parameter that is defined by your system as an Identifier of the transaction for the CustomerPayBillOnline transaction type.
	TransactionDesc   string `json:"TransactionDesc,omitempty"`   // This is any additional information/comment that can be sent along with the request
}

// ExpressQueryReq struct.
type ExpressQueryReq struct {
	PassKey           string `json:"PassKey,omitempty"`           // This is a passkey which is generated by Safaricom for use when making Lipa Na M-Pesa Online Payment API requests.
	BusinessShortCode uint64 `json:"BusinessShortCode,omitempty"` // This is organizations shortcode (Paybill or Buygoods - A 5 to 7 digit account number) used to identify an organization and receive the transaction.
	Password          string `json:"Password,omitempty"`          // This is the password used for encrypting the request sent: A base64 encoded string.
	Timestamp         string `json:"Timestamp,omitempty"`         // This is the Timestamp of the transaction, normally in the formart of YEAR+MONTH+DATE+HOUR+MINUTE+SECOND (YYYYMMDDHHMMSS)
	CheckoutRequestID string `json:"CheckoutRequestID,omitempty"` // This is a global unique identifier of the processed checkout transaction request.
}

// GenerateQRReq struct.
type GenerateQRReq struct {
	MerchantName string `json:"MerchantName,omitempty"` // Name of the Company/M-Pesa Merchant Name
	RefNo        string `json:"RefNo,omitempty"`        // Transaction Reference
	Amount       uint64 `json:"Amount,omitempty"`       // The total amount for the sale/transaction
	TrxCode      string `json:"TrxCode,omitempty"`      // Transaction Type. Can be SB, WA, PB, SM, BG
	CPI          string `json:"CPI,omitempty"`          // Credit Party Identifier. Can be a Mobile Number, Business Number, Agent Till, Paybill or Business number, Merchant Buy Goods.
	Size         string `json:"Size,omitempty"`         // Size of the QR code image in pixels. QR code image will always be a square image.
}

// C2BRegisterURLReq struct.
type C2BRegisterURLReq struct {
	ValidationURL   string `json:"ValidationURL,omitempty"`   // This is the URL that receives the validation request from API upon payment submission. The validation URL is only called if external validation on the registered shortcode is enabled. (By default external validation is disabled)
	ConfirmationURL string `json:"ConfirmationURL,omitempty"` // Thie is the URL that receives the confirmation request from API upon payment completion
	ShortCode       uint64 `json:"ShortCode,omitempty"`       // The shortcode of the organization
	ResponseType    string `json:"ResponseType,omitempty"`    // This parameter specifies what is to happen if for any reason the validation URL is not reachable. It can be cancelled or completed.
}

// C2BSimulateReq struct.
type C2BSimulateReq struct {
	CommandID     string `json:"CommandID,omitempty"`     // This is a unique identifier of the transaction type: There are two types of these Identifiers:
	Msisdn        string `json:"Msisdn,omitempty"`        // This is the phone number initiating the C2B transaction.
	BillRefNumber string `json:"BillRefNumber,omitempty"` // This is used on CustomerPayBillOnline option only. This is where a customer is expected to enter a unique bill identifier, e.g. an Account Number.
	Amount        uint64 `json:"Amount,omitempty"`        // This is the amount being transacted.
	ShortCode     uint64 `json:"ShortCode,omitempty"`     // This is the Short Code receiving the amount being transacted.
}

// B2CPaymentReq struct.
type B2CPaymentReq struct {
	OriginatorConversationID string `json:"OriginatorConversationID,omitempty"` // This is a unique string you specify for every API request you simulate.
	CommandID                string `json:"CommandID,omitempty"`                // This is a unique command that specifies B2C transaction type.
	PartyA                   uint64 `json:"PartyA,omitempty"`                   // This is the B2C organization shortcode from which the money is sent from.
	PartyB                   uint64 `json:"PartyB,omitempty"`                   // This is the customer mobile number to receive the amount. - The number should have the country code (254) without the plus sign.
	Remarks                  string `json:"Remarks,omitempty"`                  // Any additional information to be associated with the transaction.
	InitiatorName            string `json:"InitiatorName,omitempty"`            // This is an API user created by the Business Administrator of the M-PESA Bulk disbursement account that is active and authorized to initiate B2C transactions via API.
	InitiatorPassword        string `json:"InitiatorPassword,omitempty"`        // The password of the API user. This is the same password used while creating the API user.
	SecurityCredential       string `json:"SecurityCredential,omitempty"`       // This is the value obtained after encrypting the API initiator password. The password on Sandbox has been provisioned on the simulator. However, on production the password is created when the user is being created on the M-PESA organization portal.
	QueueTimeOutURL          string `json:"QueueTimeOutURL,omitempty"`          // This is the URL to be specified in your request that will be used by API Proxy to send notification incase the payment request is timed out while awaiting processing in the queue
	ResultURL                string `json:"ResultURL,omitempty"`                // This is the URL to be specified in your request that will be used by M-PESA to send notification upon processing of the payment request.
	TransactionID            string `json:"TransactionID,omitempty"`
	Occasion                 string `json:"Occasion,omitempty"` // Any additional information to be associated with the transaction.
	Amount                   uint64 `json:"Amount,omitempty"`   // The amount of money being sent to the customer.
}

// TransactionStatusReq struct.
type TransactionStatusReq struct {
	CommandID          string `json:"CommandID,omitempty"`          // Takes only the 'TransactionStatusQuery' Command ID.
	PartyA             uint64 `json:"PartyA,omitempty"`             // Organization/MSISDN receiving the transaction
	IdentifierType     uint8  `json:"IdentifierType,omitempty"`     // Type of organization receiving the transaction
	Remarks            string `json:"Remarks,omitempty"`            // Comments that are sent along with the transaction.
	InitiatorName      string `json:"Initiator,omitempty"`          // The name of Initiator to initiating  the request
	InitiatorPassword  string `json:"InitiatorPassword,omitempty"`  // The password of the API user. This is the same password used while creating the API user.
	SecurityCredential string `json:"SecurityCredential,omitempty"` // Encrypted Credential of user getting transaction amoun
	QueueTimeOutURL    string `json:"QueueTimeOutURL,omitempty"`    // The path that stores information of time out transaction
	ResultURL          string `json:"ResultURL,omitempty"`          // The path that stores information of transaction
	TransactionID      string `json:"TransactionID,omitempty"`      // Unique identifier to identify a transaction on M-Pesa
	Occasion           string `json:"Occasion,omitempty"`
}

// AccountBalanceReq struct.
type AccountBalanceReq struct {
	CommandID          string `json:"CommandID,omitempty"`
	PartyA             uint64 `json:"PartyA,omitempty"`             // Type of organization receiving the transaction
	IdentifierType     uint8  `json:"IdentifierType,omitempty"`     // Type of organization querying for the account balance.
	Remarks            string `json:"Remarks,omitempty"`            // Comments that are sent along with the transaction.
	InitiatorName      string `json:"Initiator,omitempty"`          // The name of Initiator to initiating  the request
	InitiatorPassword  string `json:"InitiatorPassword,omitempty"`  // The password of the API user. This is the same password used while creating the API user.
	SecurityCredential string `json:"SecurityCredential,omitempty"` // Encrypted Credential of user getting transaction amoun
	QueueTimeOutURL    string `json:"QueueTimeOutURL,omitempty"`    // The path that stores information of time out transaction
	ResultURL          string `json:"ResultURL,omitempty"`          // The path that stores information of transaction
}

// ReverseReq struct.
type ReverseReq struct {
	CommandID              string `json:"CommandID,omitempty"`              // Takes only the 'TransactionReversal' Command id.
	ReceiverParty          uint64 `json:"ReceiverParty,omitempty"`          // The organization that receives the transaction.
	RecieverIdentifierType uint8  `json:"RecieverIdentifierType,omitempty"` // Type of organization that receives the transaction.
	Remarks                string `json:"Remarks,omitempty"`                // Comments that are sent along with the transaction.
	InitiatorName          string `json:"Initiator,omitempty"`              // The name of the initiator to initiate the request.
	InitiatorPassword      string `json:"InitiatorPassword,omitempty"`      // The password of the API user. This is the same password used while creating the API user.
	SecurityCredential     string `json:"SecurityCredential,omitempty"`     // Encrypted Credential of the user getting transaction amount.
	QueueTimeOutURL        string `json:"QueueTimeOutURL,omitempty"`        // The path that stores information about the time-out transaction.
	ResultURL              string `json:"ResultURL,omitempty"`              // The path that stores information about the transaction.	TransactionID string `json:"TransactionID,omitempty"`
	Occasion               string `json:"Occasion,omitempty"`               // Optional Parameter.
	Amount                 uint64 `json:"Amount,omitempty"`                 // The amount of money being sent to the customer.
	TransactionID          string `json:"TransactionID,omitempty"`          // Organization Receiving the funds.
}

// RemitTaxReq struct.
type RemitTaxReq struct {
	InitiatorName          string `json:"Initiator,omitempty"`              // The name of Initiator to initiating  the request
	InitiatorPassword      string `json:"InitiatorPassword,omitempty"`      // The password of the API user. This is the same password used while creating the API user.
	SecurityCredential     string `json:"SecurityCredential,omitempty"`     // Encrypted Credential of user getting transaction amoun
	CommandID              string `json:"CommandID,omitempty"`              // Takes only the 'TransactionStatusQuery' Command ID.
	SenderIdentifierType   uint8  `json:"SenderIdentifierType,omitempty"`   // The type of shortcode from which money is deducted. For this API, only "4" is allowed.
	RecieverIdentifierType uint8  `json:"RecieverIdentifierType,omitempty"` // The type of shortcode to which money is credited. For this API, only "4" is allowed.
	Amount                 uint64 `json:"Amount,omitempty"`                 // The amount of money being sent to the customer.
	PartyA                 uint64 `json:"PartyA,omitempty"`                 // This is your own shortcode from which the money will be deducted.
	PartyB                 uint64 `json:"PartyB,omitempty"`                 // The account to which money will be credited.
	AccountReference       string `json:"AccountReference,omitempty"`       // The payment registration number (PRN) issued by KRA.
	QueueTimeOutURL        string `json:"QueueTimeOutURL,omitempty"`        // The path that stores information of time out transaction
	ResultURL              string `json:"ResultURL,omitempty"`              // The path that stores information of transaction
	Remarks                string `json:"Remarks,omitempty"`                // Comments that are sent along with the transaction.
}
