version: "3.7"

networks:
  mpesaoverlay-base-net:
    driver: bridge

services:
  grpc:
    image: ghcr.io/0x6flab/mpesaoverlay/grpc:${MO_RELEASE_TAG}
    container_name: mpesaoverlay-grpc
    restart: on-failure
    environment:
      MO_LOG_LEVEL: ${MO_LOG_LEVEL}
      MPESA_CONSUMER_KEY: ${MPESA_CONSUMER_KEY}
      MPESA_CONSUMER_SECRET: ${MPESA_CONSUMER_SECRET}
      MPESA_BASE_URL: ${MPESA_BASE_URL}
      MO_GRPC_URL: ${MO_GRPC_URL}
      MO_GRPC_SERVER_CERT: ${MO_GRPC_SERVER_CERT}
      MO_GRPC_SERVER_KEY: ${MO_GRPC_SERVER_KEY}
      MO_PROMETHEUS_URL: ${MO_PROMETHEUS_URL}
    ports:
      - ${MO_GRPC_PORT}:${MO_GRPC_PORT}
    networks:
      - mpesaoverlay-base-net

  mqtt:
    image: ghcr.io/0x6flab/mpesaoverlay/mqtt:${MO_RELEASE_TAG}
    container_name: mpesaoverlay-mqtt
    restart: on-failure
    environment:
      MO_LOG_LEVEL: ${MO_LOG_LEVEL}
      MPESA_CONSUMER_KEY: ${MPESA_CONSUMER_KEY}
      MPESA_CONSUMER_SECRET: ${MPESA_CONSUMER_SECRET}
      MPESA_BASE_URL: ${MPESA_BASE_URL}
      MO_MQTT_URL: ${MO_MQTT_URL}
      MO_MQTT_SERVER_CERT: ${MO_MQTT_SERVER_CERT}
      MO_MQTT_SERVER_KEY: ${MO_MQTT_SERVER_KEY}
      MO_PROMETHEUS_URL: ${MO_PROMETHEUS_URL}
    ports:
      - ${MO_MQTT_PORT}:${MO_MQTT_PORT}
    networks:
      - mpesaoverlay-base-net

  prometheus-pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: mpesaoverlay-prometheus-pushgateway
    restart: on-failure
    ports:
      - ${MO_PROMETHEUS_PUSH_GATEWAY_PORT}:${MO_PROMETHEUS_PUSH_GATEWAY_PORT}
    networks:
      - mpesaoverlay-base-net
