FROM scratch
LABEL org.opencontainers.image.source https://github.com/0x6flab/mpesaoverlay
ARG SVC
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY mpesa-$SVC /exe
ENTRYPOINT ["/exe"]
