version: "3.7"

networks:
  mpesaoverlay-base-net:
    driver: bridge

volumes:
  mpesaoverlay-grafana-loki:
  mpesaoverlay-grafana:

services:
  proxy:
    image: traefik:v2.10.4
    container_name: mpesaoverlay-traefik
    restart: on-failure
    depends_on:
      - grpc-adapter
      - mqtt-adapter
    ports:
      - ${MO_HTTP_PORT}:${MO_HTTP_PORT}
      - ${MO_HTTPS_PORT}:${MO_HTTPS_PORT}
      - ${MO_MQTT_PORT}:${MO_MQTT_PORT}
      - ${MO_MQTTS_PORT}:${MO_MQTTS_PORT}
      - 8080:8080 # dashboard
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml
    networks:
      - mpesaoverlay-base-net

  grpc-adapter:
    image: ghcr.io/0x6flab/mpesaoverlay/grpc:${MO_RELEASE_TAG}
    container_name: mpesaoverlay-grpc
    restart: on-failure
    environment:
      MO_LOG_LEVEL: ${MO_LOG_LEVEL}
      MPESA_CONSUMER_KEY: ${MPESA_CONSUMER_KEY}
      MPESA_CONSUMER_SECRET: ${MPESA_CONSUMER_SECRET}
      MPESA_BASE_URL: ${MPESA_BASE_URL}
      MO_GRPC_URL: ${MO_GRPC_URL}
      MO_GRPC_SERVER_CERT: ${MO_GRPC_SERVER_CERT}
      MO_GRPC_SERVER_KEY: ${MO_GRPC_SERVER_KEY}
      MO_PROMETHEUS_URL: ${MO_PROMETHEUS_URL}
    networks:
      - mpesaoverlay-base-net

  mqtt-adapter:
    image: ghcr.io/0x6flab/mpesaoverlay/mqtt:${MO_RELEASE_TAG}
    container_name: mpesaoverlay-mqtt
    restart: on-failure
    environment:
      MO_LOG_LEVEL: ${MO_LOG_LEVEL}
      MPESA_CONSUMER_KEY: ${MPESA_CONSUMER_KEY}
      MPESA_CONSUMER_SECRET: ${MPESA_CONSUMER_SECRET}
      MPESA_BASE_URL: ${MPESA_BASE_URL}
      MO_MQTT_URL: ${MO_MQTT_URL}
      MO_MQTT_SERVER_CERT: ${MO_MQTT_SERVER_CERT}
      MO_MQTT_SERVER_KEY: ${MO_MQTT_SERVER_KEY}
      MO_PROMETHEUS_URL: ${MO_PROMETHEUS_URL}
    networks:
      - mpesaoverlay-base-net

  prometheus-pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: mpesaoverlay-prometheus-pushgateway
    restart: on-failure
    ports:
      - ${MO_PROMETHEUS_PUSH_GATEWAY_PORT}:${MO_PROMETHEUS_PUSH_GATEWAY_PORT}
    networks:
      - mpesaoverlay-base-net

  loki:
    image: grafana/loki:2.9.1
    container_name: mpesaoverlay-loki
    restart: on-failure
    ports:
      - ${MO_LOKI_PORT}
    volumes:
      - mpesaoverlay-grafana-loki:/loki
    networks:
      - mpesaoverlay-base-net

  promtail:
    image: grafana/promtail:2.9.1
    container_name: mpesaoverlay-promtail
    restart: on-failure
    volumes:
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - mpesaoverlay-base-net

  grafana:
    image: grafana/grafana:10.1.4
    container_name: mpesaoverlay-grafana
    restart: on-failure
    ports:
      - ${MO_GRAFANA_PORT}:${MO_GRAFANA_PORT}
    volumes:
      - mpesaoverlay-grafana:/var/lib/grafana
      - ./grafana/example.json:/var/lib/grafana/dashboards/example.json
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/loki.yaml
    networks:
      - mpesaoverlay-base-net
