// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: grpc/responses.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *AccountBalanceResp) Reset() {
	*x = AccountBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceResp) ProtoMessage() {}

func (x *AccountBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceResp.ProtoReflect.Descriptor instead.
func (*AccountBalanceResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBalanceResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type B2CPaymentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *B2CPaymentResp) Reset() {
	*x = B2CPaymentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *B2CPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*B2CPaymentResp) ProtoMessage() {}

func (x *B2CPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use B2CPaymentResp.ProtoReflect.Descriptor instead.
func (*B2CPaymentResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{1}
}

func (x *B2CPaymentResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type C2BRegisterURLResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *C2BRegisterURLResp) Reset() {
	*x = C2BRegisterURLResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2BRegisterURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BRegisterURLResp) ProtoMessage() {}

func (x *C2BRegisterURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BRegisterURLResp.ProtoReflect.Descriptor instead.
func (*C2BRegisterURLResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{2}
}

func (x *C2BRegisterURLResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type C2BSimulateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *C2BSimulateResp) Reset() {
	*x = C2BSimulateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2BSimulateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2BSimulateResp) ProtoMessage() {}

func (x *C2BSimulateResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2BSimulateResp.ProtoReflect.Descriptor instead.
func (*C2BSimulateResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{3}
}

func (x *C2BSimulateResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type ErrorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Code      string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorResp) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *ErrorResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExpressQueryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseDescription string `protobuf:"bytes,1,opt,name=responseDescription,proto3" json:"responseDescription,omitempty"`
	ResponseCode        string `protobuf:"bytes,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	MerchantRequestID   string `protobuf:"bytes,3,opt,name=merchantRequestID,proto3" json:"merchantRequestID,omitempty"`
	CheckoutRequestID   string `protobuf:"bytes,4,opt,name=checkoutRequestID,proto3" json:"checkoutRequestID,omitempty"`
	CustomerMessage     string `protobuf:"bytes,5,opt,name=customerMessage,proto3" json:"customerMessage,omitempty"`
	ResultCode          string `protobuf:"bytes,6,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ResultDesc          string `protobuf:"bytes,7,opt,name=resultDesc,proto3" json:"resultDesc,omitempty"`
}

func (x *ExpressQueryResp) Reset() {
	*x = ExpressQueryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressQueryResp) ProtoMessage() {}

func (x *ExpressQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressQueryResp.ProtoReflect.Descriptor instead.
func (*ExpressQueryResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{5}
}

func (x *ExpressQueryResp) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

func (x *ExpressQueryResp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *ExpressQueryResp) GetMerchantRequestID() string {
	if x != nil {
		return x.MerchantRequestID
	}
	return ""
}

func (x *ExpressQueryResp) GetCheckoutRequestID() string {
	if x != nil {
		return x.CheckoutRequestID
	}
	return ""
}

func (x *ExpressQueryResp) GetCustomerMessage() string {
	if x != nil {
		return x.CustomerMessage
	}
	return ""
}

func (x *ExpressQueryResp) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

func (x *ExpressQueryResp) GetResultDesc() string {
	if x != nil {
		return x.ResultDesc
	}
	return ""
}

type ExpressSimulateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseDescription string `protobuf:"bytes,1,opt,name=responseDescription,proto3" json:"responseDescription,omitempty"`
	ResponseCode        string `protobuf:"bytes,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	MerchantRequestID   string `protobuf:"bytes,3,opt,name=merchantRequestID,proto3" json:"merchantRequestID,omitempty"`
	CheckoutRequestID   string `protobuf:"bytes,4,opt,name=checkoutRequestID,proto3" json:"checkoutRequestID,omitempty"`
	CustomerMessage     string `protobuf:"bytes,5,opt,name=customerMessage,proto3" json:"customerMessage,omitempty"`
}

func (x *ExpressSimulateResp) Reset() {
	*x = ExpressSimulateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressSimulateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressSimulateResp) ProtoMessage() {}

func (x *ExpressSimulateResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressSimulateResp.ProtoReflect.Descriptor instead.
func (*ExpressSimulateResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{6}
}

func (x *ExpressSimulateResp) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

func (x *ExpressSimulateResp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *ExpressSimulateResp) GetMerchantRequestID() string {
	if x != nil {
		return x.MerchantRequestID
	}
	return ""
}

func (x *ExpressSimulateResp) GetCheckoutRequestID() string {
	if x != nil {
		return x.CheckoutRequestID
	}
	return ""
}

func (x *ExpressSimulateResp) GetCustomerMessage() string {
	if x != nil {
		return x.CustomerMessage
	}
	return ""
}

type GenerateQRResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseDescription string `protobuf:"bytes,1,opt,name=responseDescription,proto3" json:"responseDescription,omitempty"`
	ResponseCode        string `protobuf:"bytes,2,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	RequestID           string `protobuf:"bytes,3,opt,name=requestID,proto3" json:"requestID,omitempty"`
	QRCode              string `protobuf:"bytes,4,opt,name=qRCode,proto3" json:"qRCode,omitempty"`
}

func (x *GenerateQRResp) Reset() {
	*x = GenerateQRResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateQRResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRResp) ProtoMessage() {}

func (x *GenerateQRResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRResp.ProtoReflect.Descriptor instead.
func (*GenerateQRResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateQRResp) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

func (x *GenerateQRResp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *GenerateQRResp) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *GenerateQRResp) GetQRCode() string {
	if x != nil {
		return x.QRCode
	}
	return ""
}

type RemitTaxResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *RemitTaxResp) Reset() {
	*x = RemitTaxResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemitTaxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemitTaxResp) ProtoMessage() {}

func (x *RemitTaxResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemitTaxResp.ProtoReflect.Descriptor instead.
func (*RemitTaxResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{8}
}

func (x *RemitTaxResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type ReverseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *ReverseResp) Reset() {
	*x = ReverseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResp) ProtoMessage() {}

func (x *ReverseResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResp.ProtoReflect.Descriptor instead.
func (*ReverseResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{9}
}

func (x *ReverseResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type TokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Expiry      string `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *TokenResp) Reset() {
	*x = TokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResp) ProtoMessage() {}

func (x *TokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResp.ProtoReflect.Descriptor instead.
func (*TokenResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{10}
}

func (x *TokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResp) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

type TransactionStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidResp *ValidResp `protobuf:"bytes,1,opt,name=validResp,proto3" json:"validResp,omitempty"`
}

func (x *TransactionStatusResp) Reset() {
	*x = TransactionStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusResp) ProtoMessage() {}

func (x *TransactionStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusResp.ProtoReflect.Descriptor instead.
func (*TransactionStatusResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionStatusResp) GetValidResp() *ValidResp {
	if x != nil {
		return x.ValidResp
	}
	return nil
}

type ValidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginatorConversationID string `protobuf:"bytes,1,opt,name=originatorConversationID,proto3" json:"originatorConversationID,omitempty"`
	ConversationID           string `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	ResponseDescription      string `protobuf:"bytes,3,opt,name=responseDescription,proto3" json:"responseDescription,omitempty"`
	ResponseCode             string `protobuf:"bytes,4,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
}

func (x *ValidResp) Reset() {
	*x = ValidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_responses_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidResp) ProtoMessage() {}

func (x *ValidResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_responses_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidResp.ProtoReflect.Descriptor instead.
func (*ValidResp) Descriptor() ([]byte, []int) {
	return file_grpc_responses_proto_rawDescGZIP(), []int{12}
}

func (x *ValidResp) GetOriginatorConversationID() string {
	if x != nil {
		return x.OriginatorConversationID
	}
	return ""
}

func (x *ValidResp) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *ValidResp) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

func (x *ValidResp) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

var File_grpc_responses_proto protoreflect.FileDescriptor

var file_grpc_responses_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65,
	0x72, 0x6c, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x50, 0x0a, 0x12, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3a, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61,
	0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4c, 0x0a, 0x0e, 0x42,
	0x32, 0x43, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a,
	0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x09,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x32, 0x42,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3a, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61,
	0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4d, 0x0a, 0x0f, 0x43,
	0x32, 0x42, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a,
	0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x57, 0x0a, 0x09, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0xae, 0x02, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c,
	0x0a, 0x11, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x22, 0xf1, 0x01, 0x0a, 0x13, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x13,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x51, 0x52, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x13, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x71, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x71, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x69, 0x74,
	0x54, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65,
	0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x49, 0x0a, 0x0b, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3a, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65,
	0x72, 0x6c, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x45,
	0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x53, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a,
	0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x70, 0x65, 0x73, 0x61, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc5, 0x01, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x18, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x13,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_responses_proto_rawDescOnce sync.Once
	file_grpc_responses_proto_rawDescData = file_grpc_responses_proto_rawDesc
)

func file_grpc_responses_proto_rawDescGZIP() []byte {
	file_grpc_responses_proto_rawDescOnce.Do(func() {
		file_grpc_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_responses_proto_rawDescData)
	})
	return file_grpc_responses_proto_rawDescData
}

var file_grpc_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_grpc_responses_proto_goTypes = []interface{}{
	(*AccountBalanceResp)(nil),    // 0: mpesaoverlay.grpc.AccountBalanceResp
	(*B2CPaymentResp)(nil),        // 1: mpesaoverlay.grpc.B2CPaymentResp
	(*C2BRegisterURLResp)(nil),    // 2: mpesaoverlay.grpc.C2BRegisterURLResp
	(*C2BSimulateResp)(nil),       // 3: mpesaoverlay.grpc.C2BSimulateResp
	(*ErrorResp)(nil),             // 4: mpesaoverlay.grpc.ErrorResp
	(*ExpressQueryResp)(nil),      // 5: mpesaoverlay.grpc.ExpressQueryResp
	(*ExpressSimulateResp)(nil),   // 6: mpesaoverlay.grpc.ExpressSimulateResp
	(*GenerateQRResp)(nil),        // 7: mpesaoverlay.grpc.GenerateQRResp
	(*RemitTaxResp)(nil),          // 8: mpesaoverlay.grpc.RemitTaxResp
	(*ReverseResp)(nil),           // 9: mpesaoverlay.grpc.ReverseResp
	(*TokenResp)(nil),             // 10: mpesaoverlay.grpc.TokenResp
	(*TransactionStatusResp)(nil), // 11: mpesaoverlay.grpc.TransactionStatusResp
	(*ValidResp)(nil),             // 12: mpesaoverlay.grpc.ValidResp
}
var file_grpc_responses_proto_depIdxs = []int32{
	12, // 0: mpesaoverlay.grpc.AccountBalanceResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 1: mpesaoverlay.grpc.B2CPaymentResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 2: mpesaoverlay.grpc.C2BRegisterURLResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 3: mpesaoverlay.grpc.C2BSimulateResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 4: mpesaoverlay.grpc.RemitTaxResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 5: mpesaoverlay.grpc.ReverseResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	12, // 6: mpesaoverlay.grpc.TransactionStatusResp.validResp:type_name -> mpesaoverlay.grpc.ValidResp
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_responses_proto_init() }
func file_grpc_responses_proto_init() {
	if File_grpc_responses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*B2CPaymentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2BRegisterURLResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2BSimulateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressQueryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressSimulateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateQRResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemitTaxResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_responses_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_responses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_responses_proto_goTypes,
		DependencyIndexes: file_grpc_responses_proto_depIdxs,
		MessageInfos:      file_grpc_responses_proto_msgTypes,
	}.Build()
	File_grpc_responses_proto = out.File
	file_grpc_responses_proto_rawDesc = nil
	file_grpc_responses_proto_goTypes = nil
	file_grpc_responses_proto_depIdxs = nil
}
