global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mpesaoverlay
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    follow_redirects: true
    enable_http2: true
    scheme: http
    static_configs:
      - targets:
          - prometheus-pushgateway:9091
