name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --no-config --disable-all --enable gosimple --enable govet --enable unused --enable misspell --enable revive --enable godot --enable gocritic --enable unconvert --enable whitespace --enable errorlint --enable nlreturn --timeout 3m

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -vet=off  -covermode=count -coverprofile cover.out ./...

    # - name: Convert coverage.out to coverage.lcov
    #   uses: jandelgado/gcov2lcov-action@v1.0.6
    # - name: Coveralls
    #   uses: coverallsapp/github-action@v1.1.2
    #   with:
    #     github-token: ${{ secrets.github_token }}
    #     path-to-lcov: coverage.lcov
